import React from 'react'
import './Secondpage.css'
import Button3 from './3button'
function Project() {
  return (
    <div className="main-product-page">
    <div className="heading-box">
   <span className="Common-word-product">1 Click</span><span className="product-name">  Project Funding</span>
   <div className="rectline1"></div>
    </div>
       <Button3/>
    <div className="para1-salaryadv">
      <p>
• 1 Click Capital’s Project Funding is a complete financial solution to fund
 your project start to end.</p>
<p> •This kind of funding is a long term funding, where the debt used to finance
 the project is paid back from the cash flow generated by the project.
 <p>•Project Financing is ideal for ventures requiring huge amount of equity and debt.</p>
<p></p>•PF loan structure relies mainly on the project’s cash flow for its repayment
 strategy.<p></p>•Project funding is the means by which the money required to undertake a project,
 or program is secured and then made available as required.
</p>
    </div></div>
  )
}

export default Project